var palavras = ["AMARELO", "CANECA", "ELEFANTE", "ESCOLA", "LIMONADA", "UMBIGO", "PIJAMA", "AFILHADO", "AMENDOIM", "BASQUETE", "FUTEBOL", "CAMINHO", "SISTEMA", "CHICLETE", "CHUVEIRO", "COELHO", "CONTEXTO", "BANHEIRO", "EMPENHO", "DINHEIRO", "SERENATA", "PEDESTRE", "ADVOGADO", "CACTO", "GNOMO", "RITMO"];

console.log(palavras.length);